spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rs_ecommerce
    username: root
    password: root
    tomcat.max-wait: 20000
    tomcat.max-active: 50
    tomcat.max-idle: 20
    tomcat.min-idle: 15
    validationQuery: SELECT 1
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: update

management:
  server:
    port: 8091
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"